### ISSUE TITLE
Failing builds for django-14

### ISSUE THREAD

**Issue by catskul** [jezdez/django-constance#109]
As seen here:

https://travis-ci.org/jezdez/django-constance

```
======================================================================
ERROR: test_changelist (tests.test_admin.TestAdmin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jezdez/django-constance/tests/test_admin.py", line 25, in test_changelist
    response = self.options.changelist_view(request, {})
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/travis/build/jezdez/django-constance/constance/admin.py", line 175, in changelist_view
    context, context_instance=context_instance)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 176, in render_to_string
    return t.render(context_instance)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/test/utils.py", line 63, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: admin/base_site.html
======================================================================
ERROR: test_custom_auth (tests.test_admin.TestAdmin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jezdez/django-constance/tests/test_admin.py", line 45, in test_custom_auth
    response = self.options.changelist_view(request, {})
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/travis/build/jezdez/django-constance/constance/admin.py", line 175, in changelist_view
    context, context_instance=context_instance)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 176, in render_to_string
    return t.render(context_instance)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/test/utils.py", line 63, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
    return node.render(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "/home/travis/build/jezdez/django-constance/.tox/py27-django-14/lib/python2.7/site-packages/django/template/loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: admin/base_site.html
----------------------------------------------------------------------
Ran 8 tests in 0.463s
FAILED (errors=2)
Destroying test database for alias 'default' (':memory:')...
ERROR: InvocationError: '/home/travis/build/jezdez/django-constance/.tox/py27-django-14/bin/coverage run /home/travis/build/jezdez/django-constance/.tox/py27-django-14/bin/django-admin.py test --settings=tests.settings -v2'
___________________________________ summary ____________________________________
ERROR:   py27-django-14: commands failed
```

**Comment by jezdez** [comment]
This is not not supported anymore.
