### ISSUE TITLE
Update docs to describe how to write tests for code using constance?

### ISSUE THREAD

**Issue by IanLee1521** [jezdez/django-constance#94]
I'll be happy to submit a pull request if I can figure this out, as someone else might have similar issues.

I'm trying to update my tests for code that used to make use of static settings in my `settings.py` file, now that I have switched to using constance.

Previously:

``` python
# settings.py
...
MY_SETTING = ''

# models.py
from django.conf import settings

def foo():
    if settings.MY_SETTING == 'VALUE':
        return 'foo'
    return 'bar'

# tests.py
import unittest
from django.conf import settings
from .models import foo

class MyTest(unittest.TestCase):
    def test_foo(self):
        settings.MY_SETTING = 'VALUE'
        self.assertEqual(foo(), 'foo')
```

And then for all my tests I could try setting `settings.MY_SETTING` appropriately and test the response:

``` shell
Creating test database for alias 'default'...
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
Destroying test database for alias 'default'...
```

I tried converting this converted this to:

``` python
# settings.py
...
INSTALLED_APPS += ('constance',)
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_CONFIG = {
    'MY_SETTING': ('', ''),
}


# models.py
import constance

def foo():
    if constance.config.MY_SETTING == 'VALUE':
        return 'foo'
    return 'bar'
```

And attempted to test it by setting the value directly:

``` python
# tests.py
import unittest
from . import models

class MyTest(unittest.TestCase):
    def test_foo(self):
        models.constance.config.MY_SETTING = ('VALUE', '')
        self.assertEqual(models.foo(), 'foo')
```

Which returns:

``` shell
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_foo (foo.tests.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ianlee1521/foo/foo/tests.py", line 6, in test_foo
    models.constance.config.MY_SETTING = ('VALUE', '')
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/utils/functional.py", line 253, in __setattr__
    setattr(self._wrapped, name, value)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/constance/base.py", line 27, in __setattr__
    self._backend.set(key, value)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/constance/backends/database/__init__.py", line 82, in set
    key=self.add_prefix(key), defaults={'value': value}
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 422, in get_or_create
    return self.get(**lookup), False
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: constance_config

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

Alternatively, I tried using mock:

``` python
# tests.py
import unittest
import mock
from .models import foo

class MyTest(unittest.TestCase):
    @mock.patch('foo.models.constance.config.MY_SETTING')
    def test_foo(self, mock_config):
        mock_config.return_value = 'VALUE'
        self.assertEqual(foo(), 'foo')
```

But with very similar results:

``` shell
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_foo (foo.tests.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/mock.py", line 1236, in get_original
    original = getattr(target, name, DEFAULT)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/constance/base.py", line 17, in __getattr__
    result = self._backend.get(key)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/constance/backends/database/__init__.py", line 72, in get
    value = self._model._default_manager.get(key=key).value
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: constance_config

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

Any thoughts? This seems like it is related to #84? And maybe similar (ish) to #77?

**Comment by IanLee1521** [comment]
Alright, after playing around with it for a bit longer I was able to get ride of the `OperationalError`, but still not getting the correct value returned, I'm guessing this might be more of a mock issue?

``` python
# tests.py
import unittest
import mock
from .models import foo

class MyTest(unittest.TestCase):
    @mock.patch('foo.models.constance.config')
    def test_foo(self, mock_config):
        mock_config.MY_SETTING.return_value = 'VALUE'
        self.assertEqual(foo(), 'foo')
```

Output:

``` shell
Creating test database for alias 'default'...
F
======================================================================
FAIL: test_foo (foo.tests.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ianlee1521/.local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/ianlee1521/foo/foo/tests.py", line 9, in test_foo
    self.assertEqual(foo(), 'foo')
AssertionError: 'bar' != 'foo'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

**Comment by xpostudio4** [comment]
I would like to know why you did make to solve the OperationalError with constance.

**Comment by djm** [comment]
@IanLee1521 @xpostudio4 

Using your code as an example, you probably want to do something more like this:

```
# tests.py
import unittest
import mock
from .models import foo

class MyTest(unittest.TestCase):
    @mock.patch('foo.models.config')
    def test_foo(self, mock_config):
        mock_config.MY_SETTING = 'VALUE'
        self.assertEqual(foo(), 'foo')
```

This **assumes** that in your `.models.py` file you are importing `constance` at the top with the following line: `from constance import config`, which is the way recommended in the docs.

The key points here being:

* you want to patch the object being imported into the namespace.
* `.return_value` is an attribute that mock uses to set the return value for a mocked method/function. You want to access a setting which is an attribute in this instance, so you can simply set it on the mocked object.

**Comment by IanLee1521** [comment]
Hmm, yes that probably would have worked better. I'll give that a shot. Could you point me to the reference for doing `from constance import config` as the preferred way? I've been doing `import constance` and then accessing `constance.config.VALUE` that way.

Cheers.

**Comment by djm** [comment]
@IanLee1521 Sure.

The [Python examples in the docs](http://django-constance.readthedocs.org/en/latest/#python) state importing the `config` object that way.

However, it is kind of irrelevant (provided constance isn't doing anything funky), the key takeaway from this is that with mock, you need to patch the object/module in the location that it is being imported.

Therefore, to do it with your way of importing, it would look more like this:

```
# tests.py
import unittest
import mock
from .models import foo

class MyTest(unittest.TestCase):
    @mock.patch('foo.models.constance')
    def test_foo(self, mock_constance):
        mock_constance.config.MY_SETTING = 'VALUE'
        self.assertEqual(foo(), 'foo')
```

However, I would argue that this way is slightly less obvious and more verbose.

**Comment by chornsby** [comment]
If my PR #104 is ever merged you'll be able to use a decorator in a similar way that you'd test [Django settings](https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.override_settings).

```python

# models.py
from constance import config

def foo():
    if config.MY_SETTING == 'VALUE':
        return 'foo'
    return 'bar'

# tests.py
from django.test import TestCase

from constance.test import override_config

from .models import foo


class MyTestCase(TestCase):
    """"Test foo() returns correct value with different config settings.""""

    @override_config("MY_SETTING", "VALUE")
    def test_foo_when_my_setting_is_set_to_value(self):
        self.assertEqual(foo(), "foo")

    @override_config("MY_SETTING", "SOMETHING_ELSE")
    def test_foo_when_my_setting_is_not_set_to_value(self):
        self.assertEqual(foo(), "bar")

```

**Comment by jezdez** [comment]
Closing thanks to @chornsby.
